### ISSUE TITLE
TypeError: Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by cmz97** [taranich/crawler#1]
/Users/ChengMing/Downloads/crawler-master/crawler.js:72
    for(var album in albums.response.items){
                                     ^

TypeError: Cannot read property 'items' of undefined
    at getAlbums (/Users/ChengMing/Downloads/crawler-master/crawler.js:72:38)
    at IncomingMessage.<anonymous> (/Users/ChengMing/Downloads/crawler-master/crawler.js:61:7)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by taranich** [comment]
VK has changed their API and now it requires fetching access key before calling getAlbums method.

**Comment by cmz97** [comment]
Gotcha
